
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfmqaqmrtiiwcarhlrfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmbXFhcW1ydGlpd2NhcmhscmZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MDU5MjAsImV4cCI6MjA1NDk4MTkyMH0.jDORPF-o4OG-0TWDUTkXR4orIbQcQ_PbZ130HDJD6Hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
